# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: dotnet restore # runs during prebuild
    command: dotnet run

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 5080
    onOpen: open-preview
