media_folder: "input/assets"

backend:
  name: git-gateway
  branch: master
  repo: olevett/sedos.co.uk


collections:
  - name: "shows"
    label: "Show"
    description: >
      Somewhere to put shows
    folder: "input/shows"
    slug: "{{title}}"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Subtitle", name: "subtitle", widget: "string", tagname: "h2"}
      - name: showtimes
        label: Show times
        widget: list
        fields:
          - {wlabel: "show time", widget: "datetime", format: "YYYY-MM-DD hh:mmZ"}
      - {label: "Show details", name: "body", widget: "markdown"}
  - name: "show-details" 
    label: "Show Details"
    description: >
      Details about shows
    folder: "input/show-details"
    slug: "{{title}}"
    create: true
    fields:
      - {label: "Show", name: "show", widget: "relation", collection: "shows", searchFields: "[title]", valueField: "title"}
      - {label: "Section", name: "section", widget: "string"}
      - {label: "Section content", name: "body", widget: "markdown"}
  - name: "news" 
    label: "News"
    description: >
      News articles
    folder: "input/news"
    slug: "{{title}}"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Publish Date", name: "date", widget: "date", format: "YYYY-MM-DD"}
      - {label: "Article content", name: "body", widget: "markdown"}
  - name: "events" 
    label: "Event"
    description: >
      Events
    folder: "input/events"
    slug: "{{title}}"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Publish Date", name: "date", widget: "date", format: "YYYY-MM-DD"}
      - {label: "Article content", name: "body", widget: "markdown"}
      - name: times
        label: Event times
        widget: list
        fields:
          - {wlabel: "event time", widget: "datetime", format: "YYYY-MM-DD hh:mmZ"}
      - label: "Featured Image"
        name: "image"
        widget: "image"
