media_folder: input/assets
public_folder: /assets
publish_mode: editorial_workflow

backend:
  name: git-gateway
  branch: main
  repo: sedostheatre/sedos.co.uk

slug:
  encoding: ascii
  clean_accents: true

collections:
  - name: "shows"
    label: "Show"
    description: Somewhere to put shows
    folder: "input/shows"
    slug: "{{fields.year}}-{{title}}"
    create: true
    summary: "{{fields.year}} {{title}}"
    sortable_fields: ['title', 'year']
    fields:
      - label: Title
        name: title
        widget: string
        tagname: h1
      - label: Year
        name: year
        widget: string
      - label: Authors
        name: authors
        widget: string
        tagname: h4
        required: false
      - label: Authors (second line)
        name: authors2
        widget: string
        tagname: h4
        required: false
      - label: Authors (third line line)
        name: authors3
        widget: string
        tagname: h3
        required: false
      - label: Subtitle (shown on home page/show details page below authors)
        name: subtitle
        widget: string
        tagname: h2
        required: false
      - name: showtimes
        label: Show times
        widget: list
        required: false
        fields:
          - label: Show time
            widget: datetime
            name: time
            format: YYYY-MM-DD HH:mm
            dateFormat: DD-MM-YYYY
            timeFormat: HH:mm
      - name: showtime-summary
        label: Summary of show times, shown at the footer of the home page/show details header
        widget: string
        required: false
      - label: Show on home page (only applicable when show is in the past)?
        name: show-on-homepage
        widget: boolean
        required: false
      - label: Order on home page
        name: order-on-homepage
        widget: number
        required: false
      - label: Venue
        name: venue
        widget: string
        required: false
      - label: Ticket Prices
        name: ticket-prices
        widget: text
        required: false
      - label: Additional Ticket Information
        name: additional-ticket-info
        widget: text
        required: false
      - label: Primary colour (this gets used along side the header image)
        name: primary-color
        widget: string
        required: false
      - label: Header image (displayed at the top of the home page and show page)
        name: header-image
        widget: image
        required: false
      - label: Scale header image to fit (off will fill available space)
        name: header-image-contain
        widget: boolean
        default: false
        required: false
      - label: Flyer image (displayed on shows page)
        name: flyer
        widget: image
        required: false
      - label: Box office open
        name: box-office-open
        widget: boolean
        default: false
        required: false
      - label: Box Office Link
        name: box-office-link
        widget: string
        required: false
      - label: Show details
        name: body
        widget: markdown
        required: false
      - name: sections
        label: Show Details
        description: Details about shows
        widget: list
        required: false
        fields:
          - name: title
            label: Title
            widget: string
          - name: order
            label: "Order"
            widget: "number"
            default: 1
            valueType: "int"
            min: 1
            max: 100
            step: 1
          - name: body
            label: Section content
            widget: markdown
      - name: RedirectFrom
        label: Redirect From
        description: Pages on the old site to redirect from
        widget: list
        required: false
      - name: metaDescription
        width: string
        required: false
  - name: news
    label: News
    description: News articles
    folder: input/news
    slug: "{{year}}-{{month}}-{{day}}-{{title}}"
    summary: "{{year}}-{{month}}-{{day}} {{title}}"
    create: true
    fields:
      - name: title
        label: Title
        widget: string
        tagname: h1
      - name: date
        label: Publish Date
        widget: date
        format: YYYY-MM-DD
      - name: image
        label: Image (used on the home page/all news for the card tile)
        widget: image
        required: false
      - name: extract
        label: Extract (used on the home page/all news page, if an image isn't set)
        widget: string
        required: false
      - name: body
        label: Article content
        widget: markdown
      - name: RedirectFrom
        label: Redirect From
        description: Pages on the old site to redirect from
        widget: list
        required: false
      - name: metaDescription
        width: string
        required: false
  - name: events
    label: Events
    description: Events
    folder: input/events
    slug: "{{title}}"
    create: true
    fields:
      - name: title
        label: Title
        widget: string
        tagname: h1
      - name: times
        label: Event times
        widget: list
        fields:
          - label: event time
            widget: datetime
            name: time
            format: YYYY-MM-DD HH:mm
      - name: image
        label: Featured Image
        widget: image
      - name: venue
        label: Venue
        widget: string
        required: false
      - name: recurrence
        label: Event recurrence (e.g. every Tuesday) shown on the event sidebar, also shown on the home page/upcoming events cards
        widget: string
        required: false
      - label: Ticket Prices
        name: ticket-prices
        widget: text
        required: false
      - label: Event details
        name: body
        widget: markdown
      - name: metaDescription
        width: string
        required: false
  - name: regular-events
    label: Regular events
    description: regular events
    folder: input/regular-events
    slug: "{{title}}"
    create: true
    fields:
      - name: title
        label: Title
        widget: string
        tagname: h1
      - name: times
        label: Event times
        widget: list
        required: false
        fields:
          - label: event time
            widget: datetime
            name: time
            format: YYYY-MM-DD HH:mm
      - name: image
        label: Featured Image
        widget: image
        required: false
      - name: header-image
        label: Header Image
        widget: image
        required: false
      - name: venue
        label: Venue
        widget: string
        required: false
      - name: recurrence
        label: Event recurrence (e.g. every Tuesday) shown on the event sidebar, also shown on the home page/upcoming events cards
        widget: string
        required: false
      - label: Ticket Prices
        name: ticket-prices
        widget: text
        required: false
      - label: Event details
        name: body
        widget: markdown
      - name: RedirectFrom
        label: Redirect From
        description: Pages on the old site to redirect from
        widget: list
        required: false
      - name: metaDescription
        width: string
        required: false
  - name: venues
    label: Venues
    folder: input/venues
    create: true
    slug: "{{key}}"
    fields:
      - {label: name, name: name, widget: string}
      - {label: key, name: key, widget: string}
      - label: details
        name: body
        widget: markdown
  - name: about
    label: About
    folder: input/about
    create: true
    fields:
      - {label: title, name: title, widget: string}
      - {label: row, name: row, widget: number, valueType: int}
      - {label: column, name: column, widget: number, valueType: int}
      - {label: image, name: image, widget: image}
      - {label: link, name: link, widget: string, required: false}
      - {label: Details, name: body, widget: markdown, required: false}
      - name: RedirectFrom
        label: Redirect From
        description: Pages on the old site to redirect from
        widget: list
        required: false
  - name: your-visit
    label: Your Visit
    folder: input/your-visit
    create: true
    fields:
      - {label: title, name: title, widget: string}
      - {label: row, name: row, widget: number, valueType: int}
      - {label: column, name: column, widget: number, valueType: int}
      - {label: image, name: image, widget: image}
      - {label: link, name: link, widget: string, required: false}
      - {label: Details, name: body, widget: markdown, required: false}
  - name: header-images
    label: Header Images
    files:
      - label: "News"
        name: "News"
        file: "input/header-images/news.yml"
        fields:
          - {label: key, name: key, widget: hidden}
          - {label: Image, name: image-source, widget: image}
      - label: "Events"
        name: "Events"
        file: "input/header-images/events.yml"
        fields:
          - {label: key, name: key, widget: hidden}
          - {label: Image, name: image-source, widget: image}
      - label: "Get Involved"
        name: "get-involved"
        file: "input/header-images/get-involved.yml"
        fields:
          - {label: key, name: key, widget: hidden}
          - {label: Image, name: image-source, widget: image}
      - label: "About"
        name: "about"
        file: "input/header-images/about.yml"
        fields:
          - {label: key, name: key, widget: hidden}
          - {label: Image, name: image-source, widget: image}
      - label: "Your Visit"
        name: "your-visit"
        file: "input/header-images/your-visit.yml"
        fields:
          - {label: key, name: key, widget: hidden}
          - {label: Image, name: image-source, widget: image}
      - label: "Whats On"
        name: "whats-on"
        file: "input/header-images/whats-on.yml"
        fields:
          - {label: key, name: key, widget: hidden}
          - {label: Image, name: image-source, widget: image}
      - label: "Fallback"
        name: "fallback"
        file: "input/header-images/fallback.yml"
        fields:
          - {label: key, name: key, widget: hidden}
          - {label: Image, name: image-source, widget: image}
  - label: "Pages"
    name: "pages"
    files:
      - label: "Marketing group"
        name: "marketing"
        file: "input/groups/marketing.md"
        fields:
          - {label: title, name: title, widget: string}
          - {label: Details, name: body, widget: markdown, required: false}
          - name: RedirectFrom
            label: Redirect From
            description: Pages on the old site to redirect from
            widget: list
            required: false
      - label: "Membership group"
        name: "membership"
        file: "input/groups/membership.md"
        fields:
          - {label: title, name: title, widget: string}
          - {label: Details, name: body, widget: markdown, required: false}
          - name: RedirectFrom
            label: Redirect From
            description: Pages on the old site to redirect from
            widget: list
            required: false
      - label: "Production group"
        name: "production"
        file: "input/groups/production.md"
        fields:
          - {label: title, name: title, widget: string}
          - {label: Details, name: body, widget: markdown, required: false}
          - name: RedirectFrom
            label: Redirect From
            description: Pages on the old site to redirect from
            widget: list
            required: false
      - label: "Backstage"
        name: "backstage"
        file: "input/backstage.md"
        fields:
          - {label: title, name: title, widget: string}
          - {label: Details, name: body, widget: markdown, required: false}
          - name: RedirectFrom
            label: Redirect From
            description: Pages on the old site to redirect from
            widget: list
            required: false
      - label: "Hires"
        name: "hires"
        file: "input/hires.md"
        fields:
          - {label: title, name: title, widget: string}
          - {label: Details, name: body, widget: markdown, required: false}
          - name: RedirectFrom
            label: Redirect From
            description: Pages on the old site to redirect from
            widget: list
            required: false
      - label: "Thanks"
        name: "thanks"
        file: "input/thanks.md"
        fields:
          - {label: title, name: title, widget: string}
          - {label: Details, name: body, widget: markdown, required: false}
          - name: RedirectFrom
            label: Redirect From
            description: Pages on the old site to redirect from
            widget: list
            required: false
      - label: "Terms and conditions"
        name: "terms"
        file: "input/terms-and-conditions.md"
        fields:
          - {label: title, name: title, widget: string}
          - {label: Details, name: body, widget: markdown, required: false}
          - name: RedirectFrom
            label: Redirect From
            description: Pages on the old site to redirect from
            widget: list
            required: false
      - label: "Contact Us"
        name: "contact-us"
        file: "input/contact-us.md"
        fields:
          - {label: title, name: title, widget: string}
          - {label: Details, name: body, widget: markdown, required: false}
          - name: RedirectFrom
            label: Redirect From
            description: Pages on the old site to redirect from
            widget: list
            required: false
      - label: "What's On"
        name: "whats-on"
        file: "input/whats-on.md"
        fields:
          - {label: "Content Title", name: title, widget: string}
          - {label: "Document Title", name: DocumentTitle, widget: string, required: false}
          - {label: Details, name: body, widget: markdown, required: false}
          - {label: Category, name: category, widget: hidden}
          - {label: ViewStart, name: view-start, widget: hidden}
          - name: RedirectFrom
            label: Redirect From
            description: Pages on the old site to redirect from
            widget: list
            required: false
          - name: metaDescription
            width: string
            required: false
      - label: "Get involved"
        name: "get-involved"
        file: "input/get-involved.md"
        fields:
          - {label: "Content Title", name: title, widget: string}
          - {label: "Document Title", name: DocumentTitle, widget: string, required: false}
          - {label: Details, name: body, widget: markdown, required: false}
          - {label: Category, name: category, widget: hidden}
          - {label: ViewStart, name: view-start, widget: hidden}
          - {label: groups, name: view-start, widget: hidden}
          - name: RedirectFrom
            label: Redirect From
            description: Pages on the old site to redirect from
            widget: list
            required: false
          - name: metaDescription
            width: string
            required: false
      - label: "2005 review"
        name: "2005-review"
        file: "input/2005-review.md"
        fields:
          - {label: title, name: title, widget: string}
          - {label: "Review of year", name: review-of-year, widget: string}
          - {label: Details, name: body, widget: markdown, required: false}
          - name: RedirectFrom
            label: Redirect From
            description: Pages on the old site to redirect from
            widget: list
            required: false
      - label: "2006 review"
        name: "2006-review"
        file: "input/2006-review.md"
        fields:
          - {label: title, name: title, widget: string}
          - {label: "Review of year", name: review-of-year, widget: string}
          - {label: Details, name: body, widget: markdown, required: false}
          - name: RedirectFrom
            label: Redirect From
            description: Pages on the old site to redirect from
            widget: list
            required: false
      - label: "2007 review"
        name: "2007-review"
        file: "input/2007-review.md"
        fields:
          - {label: title, name: title, widget: string}
          - {label: "Review of year", name: review-of-year, widget: string}
          - {label: Details, name: body, widget: markdown, required: false}
          - name: RedirectFrom
            label: Redirect From
            description: Pages on the old site to redirect from
            widget: list
            required: false
      - label: "Policies"
        name: "policies"
        file: "input/policies.md"
        fields:
          - {label: title, name: title, widget: string}
          - {label: Details, name: body, widget: markdown, required: false}
          - name: RedirectFrom
            label: Redirect From
            description: Pages on the old site to redirect from
            widget: list
            required: false
