name: Optimise Images
on:
  workflow_dispatch:
  schedule:
    - cron: '00 23 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Optimise Images
        id: calibre
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          compressOnly: true
      - name: Create New Pull Request If Needed
        if: steps.calibre.outputs.markdown != ''
        uses: peter-evans/create-pull-request@v5
        with:
          title: 'chore: Aautomatically optimise images'
          commit-message: 'chore: Aautomatically optimise images'
          body: ${{ steps.calibre.outputs.markdown }}
